ApiKey: "None"
ApiKeyRequired: false
Url: "http://localhost:11434/api/chat"
Model: "vanilj/phi-4-unsloth"
ModelParams:
  temperature: 0.1
  max_tokens: 1000
  top_p: 1.0
  top_k: 50
  min_p: 0.5
  frequency_penalty: 0
  presence_penalty: 0
RetryCount: 3
BatchSize: 20
